- name: Fetch dotfiles from github repository
  git:
    repo: "{{ dotfiles_git }}"
    dest: "/home/{{ user }}/dotfiles"
    accept_hostkey: yes

- name: Create needed directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/home/{{ user }}/.config"

- name: link dotfiles
  file:
    src: "/home/{{ user }}/dotfiles/{{ item.src }}"
    dest: "/home/{{ user }}/{{ item.dest }}"
    state: link
    force: yes
  with_items:
    - { src: "bash/aliases", dest: ".bash_aliases" }
    - { src: "bash/profile", dest: ".profile" }
    - { src: "vim/vimrc", dest: ".vimrc" }
    - { src: "gtk-3.0", dest: ".config/gtk-3-0" }
    - { src: "xfce4", dest: ".config/xfce4" }
    - { src: "icons", dest: ".icons" }
    - { src: "themes", dest: ".themes" }