- import_tasks: ../../virtualization/tasks/virtualbox.yml
- import_tasks: ../../virtualization/tasks/vagrant.yml
- import_tasks: ../../virtualization/tasks/docker.yml
- import_tasks: mysql.yml

- name: Install php related packages
  become: true
  apt: name={{ item }} state=present
  with_items:
    - composer
    - php-cli
    
- name: Download and extract postman archive
  become: true
  unarchive:
    src: https://dl.pstmn.io/download/latest/linux64
    dest: "/opt"
    remote_src: yes
    list_files: yes
  register: new_archive

- name: Download & extract phpstorm archive
  become: true
  unarchive:
    src: https://download.jetbrains.com/webide/PhpStorm-2018.2.tar.gz
    dest: "/opt"
    remote_src: yes
    list_files: yes
  register: new_archive

- name: Rename PhpStorm directory
  become: true
  command: "mv /opt/{{ new_archive.files[0] }} /opt/phpstorm"