- name: Add dev package keys
  become: true
  apt_key: url={{ item }} state=present
  with_items:
    - https://download.docker.com/linux/debian/gpg
    - https://www.virtualbox.org/download/oracle_vbox_2016.asc

- name: Add dev repositories
  become: true
  apt_repository: repo={{ item }} state=present
  with_items:
    - "deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    - "deb https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"

- name: Remove old dev packages
  become: true
  apt: name={{ item }} state=absent
  with_items:
   - docker
   - docker-engine
   - docker.io
   - virtualbox

- name: Install dev packages
  become: true
  apt: name={{ item }} state=present
  with_items:
    - docker-ce
    - composer
    - php-cli
    - mysql-client
    - virtualbox-5.2
    - vagrant
    - wine

  become: true
  apt: deb={{ item }}
  with_items:
    - https://github.com/adobe/brackets/releases/download/release-1.13/Brackets.Release.1.13.64-bit.deb
    - https://releases.hashicorp.com/vagrant/2.1.2/vagrant_2.1.2_x86_64.deb