- include: adduser.yml

- name: Create directories
  file: name="{{ item }}" state=directory
  with_items:
    - "/home/{{ user }}/tmp"

- include: apt-update.yml
- include: basic-packages.yml
- include: themes.yml