- name: Create directories
  file: name="{{ item }}" state=directory
  with_items:
    - "/home/{{ ansible_env.USER }}/tmp"

- include: apt-update.yml
- include: basic-packages.yml
- include: xfce.yml
- include: devtools.yml
- include: teamviewer.yml
- include: google-drive.yml
- include: dotfiles.yml