- name: Install xfce packages
  apt: name={{ item }} state=present
  with_items:
    - xfce4
    - xfce4-goodies
    - xfwm4-themes
    - shiki-colors-xfwm-theme
    - adwaita-icon-theme
    - albatross-gtk-theme
    - arc-theme
    - hicolor-icon-theme